CREATE TABLE biodata(
    user_id serial PRIMARY KEY,
    Name VARCHAR NOT NULL,
    Village VARCHAR,
    Sex VARCHAR,
    DateOfBirth DATE,
    TimeOfBirth TIME,
    Reference VARCHAR,
    Age VARCHAR,
    Height VARCHAR,
    FatherName VARCHAR,
    MotherName VARCHAR,
    Address VARCHAR,
    Education VARCHAR,
    Employment VARCHAR,
    SalaryPerYear VARCHAR,
    WhatsappNo1 VARCHAR,
    WhatsappNo2 VARCHAR,
    WhatsappNo3 VARCHAR,
    MayakaAddress VARCHAR,
    Pariwar VARCHAR,
    FatherOccupation VARCHAR,
    Property VARCHAR,
    Brother VARCHAR,
    BrotherMartialStatus VARCHAR,
    Sister VARCHAR,
    SisterMaritialStatus VARCHAR,
    Color VARCHAR,
    Hobby VARCHAR,
    Mangli VARCHAR,
    DiseaseIfAny VARCHAR,
    FinallyEngagedWith VARCHAR,
    Photograph1 VARCHAR,
    Photograph2 VARCHAR,
    Photograph3 VARCHAR,
    InformationSentFollowUp VARCHAR,
    StatusRYG VARCHAR
)


INSERT INTO biodata(
    Name,
    DateOfBirth,TimeOfBirth,
    Village,Pariwar,
    FatherName,MotherName,
    Reference,
    Age,Sex,
    Height,Color,
    Address,
    Education,Employment,
    SalaryPerYear,Mangli,
    WhatsappNo1,WhatsappNo2,WhatsappNo3,
    MayakaAddress,
    FatherOccupation,
    Property,
    Brother,BrotherMartialStatus,
    Sister,SisterMaritialStatus,
    Hobby,
    DiseaseIfAny,
    Photograph1,Photograph2,Photograph3,
    InformationSentFollowUp)
    VALUES(
    '{{name_i.text}}',
    '{{DOB_i.selectedDate}}','{{TOB_i.text}}',
    '{{village_i.text}}','{{pariwar_i.text}}',
    '{{fathername_i.text}}','{{mothername_i.text}}',
    '{{reference_i.text}}',
    '{{age_i.text}}','{{sex_i.selectedOptionValue}}',
    '{{height_i.text}}','{{color_i.selectedOptionValue}}',
    '{{address_i.text}}',
    '{{education_i.text}}','{{employment_i.text}}',
    '{{salary_i.text}}','{{mangli_i.selectedOptionValue}}',
    '{{contact1_i.text}}','{{contact2_i.text}}','{{contact3_i.text}}',
    '{{mayakaaddress_i.text}}',
    '{{fatheroccupation_i.text}}',
    '{{property_i.text}}',
    '{{brother_i.text}}','{{brother_marriage_i.text}}',
    '{{sister_i.text}}','{{sister_marriage_i.text}}',
    '{{hobby_i.text}}',
    '{{disease_i.text}}',
    '{{photo1_status_i.text}}','{{photo2_status_i.text}}','{{photo3_status_i.text}}',
    '{{followup_i.text}}');



UPDATE biodata
SET
    Name='{{name_e.text}}',
    DateOfBirth='{{DOB_e.text}}',TimeOfBirth='{{TOB_e.text}}',
    Village='{{village_e.text}}',Pariwar='{{pariwar_e.text}}',
    FatherName='{{fathername_e.text}}',MotherName='{{mother_e.text}}',
    Reference='{{reference_e.text}}',
    Age='{{age_e.text}}',Sex='{{sex_e.text}}',
    Height='{{height_e.text}}',Color='{{color_e.text}}',
    Address='{{address_e.text}}',
    Education='{{education_e.text}}',Employment='{{employment_e.text}}',
    SalaryPerYear='{{salary_e.text}}',Mangli='{{mangli_e.text}}',
    WhatsappNo1='{{contact1_e.text}}',WhatsappNo2='{{contact2_e.text}}',WhatsappNo3='{{contact3_e.text}}',
    MayakaAddress='{{mayakaaddress_e.text}}',
    FatherOccupation='{{fatheroccupation_e.text}}',
    Property='{{property_e.text}}',
    Brother='{{brother_e.text}}',BrotherMartialStatus='{{brothermarraige_e.text}}',
    Sister='{{sister_e.text}}',SisterMaritialStatus='{{sistermarraige_e.text}}',
    Hobby='{{hobby_e.text}}',
    DiseaseIfAny='{{disease_e.text}}',
    Photograph1='{{photo1_status_e.text}}',Photograph2='{{photo2_status_e.text}}',Photograph3='{{photo3_status_e.text}}',
    InformationSentFollowUp='{{followup_e.text}}'
    WHERE user_id={{BiodataEditTable.selectedRow.user_id}};